### ISSUE TITLE
Allow multi-enum usage of opslogger

### ISSUE THREAD

**Issue by ravn** [EqualExperts/opslogger#6]
Currently OpsLogger only allows for a single enum for configuring the logging system.  For large modular systems this may not be a usable approach.

Would reworking OpsLoggerFactory to allow multiple calls to build() with different enums but combining the use of the same underlying BasicOpsLogger be an option?

**Comment by seanjreilly** [comment]
We could do something like that, yes.

As a workaround in the meantime, since Java generics are implemented using type erasure, you can actually do what you want with a cast:

```java
OpsLogger<Foo> foo = new OpsLoggerFactory.build();
OpsLogger<Bar> bar = (OpsLogger<Bar>) foo;
```

We could potentially encapsulate this behaviour into a method on OpsLoggerFactory, and have it perform the cast:

```java
OpsLoggerFactory factory = new OpsLoggerFactory();
OpsLogger<Foo> foo = factory.build();
OpsLogger<Bar> bar = factory.convert(Bar.class, foo); //a cast to OpsLogger<Bar> is performed inside the method
```

Or we could encapsulate the behaviour in a different class, perhaps something like this:

```java
MultiOpsLogger multiLogger = new OpsLoggerFactory().buildMulti();
multiLogger.get(Foo.class).log(Foo.MessageA, "some argument");
multiLogger.get(Bar.class).log(Bar.MessageB, "some other argument");
```

Or we could implement something in the Factory itself. I'm not as sure how that might work, and I'm a little worried about calling one of the mutator methods (like `setAsync`) after build is called, and how that might work.

Thoughts?

**Comment by ravn** [comment]
I really think that the current design with OpsLoggerFactory being able to
provide several vastly different backends, has already crossed the
complexity threshold, and should be refactored into something with less
ifs.  I think the slf4j API got it right.  Provide an interface and let the
implementor provide a backend (one for testing and one for production).

That said, I think that explicity exploiding type erasure is too much
bending ovre backwards to avoid adjusting the API.  I have some spare time
this week, so I would like to experiment a little to see how it would look.

On Fri, Apr 10, 2015 at 5:38 PM, Sean Reilly <notifications@github.com>
wrote:

> We could do something like that, yes.
>
> As a workaround in the meantime, since Java generics are implemented using
> type erasure, you can actually do what you want with a cast:
>
> OpsLogger<Foo> foo = new OpsLoggerFactory.build();OpsLogger<Bar> bar = (OpsLogger<Bar>) foo;
>
> We could potentially encapsulate this behaviour into a method on
> OpsLoggerFactory, and have it perform the cast:
>
> OpsLoggerFactory factory = new OpsLoggerFactory();OpsLogger<Foo> foo = factory.build();OpsLogger<Bar> bar = factory.convert(Bar.class, foo); //a cast to OpsLogger<Bar> is performed inside the method
>
> Or we could encapsulate the behaviour in a different class, perhaps
> something like this:
>
> MultiOpsLogger multiLogger = new OpsLoggerFactory().buildMulti();
> multiLogger.get(Foo.class).log(Foo.MessageA, "some argument");
> multiLogger.get(Bar.class).log(Bar.MessageB, "some other argument");
>
> Or we could implement something in the Factory itself. I'm not as sure how
> that might work, and I'm a little worried about calling one of the mutator
> methods (like setAsync) after build is called, and how that might work.
>
> Thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EqualExperts/opslogger/issues/6#issuecomment-91595367>
> .
>



-- 
  Thorbjørn Ravn Andersen - "...plus...Tubular Bells!"

**Comment by ravn** [comment]
Initial impression is that the underlying "log an Enum which is a LogMessage" part can relatively easily be changed into "log an Enum" all the way up to AsyncOpsLogger and BasicOpsLogger, and then the build() method can wrap a singleton OpsLoggerBase (just using a LogMessage interface)  into the  full blown OpsLogger interface (using T) with a small wrapper.

**Comment by seanjreilly** [comment]
Just out of curiosity, with a singleton performing the actual logging, how would you handle multiple log destinations/formats? For example, logging some messages to the console, some to a file, etc?

We have a definite use case with one of our clients where log messages are sent to different files, and each file contains log messages from a specific enum only.

**Comment by ravn** [comment]
An instance of OpsLoggerFactory (javax.inject.Provider<OpsLogger>?) has a
single configuration which must be frozen (which in turn speaks for
constructor dependencies) after the first call to build().

If another configuration is needed, create another instance of
OpsLoggerFactory.  is there any reason that the use case cannot be done
with the current code?


On Tue, Apr 14, 2015 at 4:12 PM, Sean Reilly <notifications@github.com>
wrote:

> Just out of curiosity, with a singleton performing the actual logging, how
> would you handle multiple log destinations/formats? For example, logging
> some messages to the console, some to a file, etc?
>
> We have a definite use case with one of our clients where log messages are
> sent to different files, and each file contains log messages from a
> specific enum only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EqualExperts/opslogger/issues/6#issuecomment-92867150>
> .
>



-- 
  Thorbjørn Ravn Andersen - "...plus...Tubular Bells!"

**Comment by ravn** [comment]
My primary concern was to have multiple enums use the same logger, not to have multiple enums have multiple loggers.

**Comment by seanjreilly** [comment]
Your use case is valid, but unfortunately, so is the other one. We have at least one project using multiple enums with multiple loggers in production right now.

As far as freezing the output of OpsLoggerFactory, I can't say that I've ever used the factory pattern and had the factory keep a reference to the result once build is called. I wonder if that would be intuitive to users. What would happen if a user accidentally calls one of the mutation methods after calling build?

**Comment by ravn** [comment]
Perhaps you would care to elaborate on the use case you mention, so I can
get a better idea of how you currently solve the problem.

These stories might be beneficial to add to the project so it is easier for
non-EqualExperts to understand the various design issues.

On Tue, Apr 14, 2015 at 5:14 PM, Sean Reilly <notifications@github.com>
wrote:

> Your use case is valid, but unfortunately, so is the other one. We have at
> least one project using multiple enums with multiple loggers in production
> right now.
>
> As far as freezing the output of OpsLoggerFactory, I can't say that I've
> ever used the factory pattern and had the factory keep a reference to the
> result once build is called. I wonder if that would be intuitive to users.
> What would happen if a user accidentally calls one of the mutation methods
> after calling build?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EqualExperts/opslogger/issues/6#issuecomment-92898707>
> .
>



-- 
  Thorbjørn Ravn Andersen - "...plus...Tubular Bells!"

**Comment by seanjreilly** [comment]
I'm afraid that the specific details are confidential, but the gist is:
- Warnings and non-critical events are output to one file.
- Critical events (somebody is paged, even at night) are output to a different file.
- The files are associated with different enums, but should have exactly the same formats otherwise.

With this use case, a single factory can be used quite easily:

```java
OpsLoggerFactory factory = new OpsLoggerFactory()
    .setStackTraceStoragePath(Paths.get("/tmp/stacktraces"))
    .setAsync(true)
    .setCorrelationIdSupplier(context) //defined somewhere else, but used for both loggers
    .setErrorHandler(TheApplication::loggingError);

OpsLogger<Foo> = factory.setPath(Paths.get("/logs/foo.log")).build();

OpsLogger<Bar> = factory.setPath(Paths.get("/logs/bar.log")).build();
```

We commonly use the factory pattern in this way: calling build, mutating one or two settings, and calling build again is a very nice way to describe building two instances with specific differences.

**Comment by ravn** [comment]
There is no tests in OpsLoggerFactoryTest which test this usecase behavior with multiple calls to build().  To my understanding this mean that my implementation is as "good" as yours, and that the usage you describe is exploiting implementation specific details.

**Comment by seanjreilly** [comment]
Hi @ravn,

Sorry for the delay in replying. I've been on holiday.

You're absolutely right that there were no tests in OpsLoggerFactory test that specified this use case behaviour. Thanks for pointing that out! I've just added some to clarify this expectation. But either way, the tests aren't an inviolable contract. Rather, I view them as expressing our current understanding of what we expect the code to do, which is entirely subject to change or rethink. Tests can always be changed if that's what we decide to do.

(As an aside, that's the reason behind the OpsLoggerFactory in the first place. I want to keep as much code as possible out of the backwards-compatibility zone, to protect our ability to make as many changes as possible.)

So please don't ever be hesitant to make a suggestion like this, even if there is a current test that would fail or need to be changed!

Now onto the main topic:  why I feel the current behaviour is a good thing to stick to.

I feel like the current approach works better with the [Principle of Least Astonishment](http://en.wikipedia.org/wiki/Principle_of_least_astonishment). Having a setter that works when it is first called, but that throws an exception (or worse, is silently ignored) doesn't feel like what the majority of users would expect to happen.

Also, introducing a new lifecycle phase (build has already been called at least once) for OpsLoggerFactory will add complexity, and as you've rightly pointed out, the implementation for that class is already complicated enough.

If we're going to add a facility to adapt an existing OpsLogger to a new LogMessage enum, I think we'd be much better served by making that behaviour explicit (either by an adapt method or some sort of MultiOpsLogger class) in a way where it can't possibly be a surprise to a user.

**Comment by ravn** [comment]
I do not have a preference for any particular behaviour.  In my experience it is just a good thing if configurations are immutable after being made ready to be used by other code.  Perhaps introducing a generic interface implemented by OpsLoggerFactory so that can be injected?

I'm looking forward to seeing what you come up with.

**Comment by seanjreilly** [comment]
> Perhaps introducing a generic interface implemented by OpsLoggerFactory so that can be injected?

I'm confused. This sounds intriguing, but I don't think I properly understand what you're suggesting here....

Is there any chance you could illustrate a very short example (even in pseudocode would be super helpful) to help me understand what you mean by this?

**Comment by seanjreilly** [comment]
@ravn: I've been thinking about this, and I think I understand now. Are you suggesting that you would like to inject an OpsLogger factory as a dependency of some class or service?

If so, that's a fascinating use case, and I'd like to hear more about it. This is the first time I've heard of anyone mention this use case — the dependency injection use case we've considered before uses created OpsLogger instances as singletons, injecting them into application classes. In this use case, OpsLoggerFactory instances are used to create dependencies, but aren't injected into anything themselves — they are only interacted with when creating the object graph.

I'd love to hear more about what you're thinking about accomplishing by injecting a factory... it seems quite interesting.

In the meantime, I'm leaning towards the MultiOpsLogger solution from above:

```java
MultiOpsLogger multiLogger = new OpsLoggerFactory().buildMulti();
OpsLogger<Foo> foo = multiLogger.build();
foo.log(Foo.MessageA, "some argument");
OpsLogger<Bar> bar = multiLogger.build();
bar.log(Bar.MessageB, "some other argument");
```

In this case, `OpsLoggerFactory` is the mutable class used to express configurations. Calling `buildMulti` "freezes" the configuration, and indeed the OpsLogger will contain a single frozen OpsLogger instance that is a singleton from that point on. (For now, it might as well just use type erasure, but it can just as easily contain a BaseOpsLogger instance, and wrap it when `build` is called, if we ever need that in the future).

In fact, since the method that returns the actual OpsLogger has the same signature on MultiOpsLogger as it does on OpsLoggerFactory, there is an opportunity to extract an interface that both classes implement.

In fact, the regular build method in OpsLoggerFactory could probably just call ```buildMulti().build()``` and then throw the MultiBuilder away — although I'd still like to keep the original method around as a convenience.

What do you think?

**Comment by seanjreilly** [comment]
Hi @ravn,

At long last, I've got something for you.

The fixes are in two pull requests for ease of review.
1. Pull Request #7 delegates the ops logger creation to internal factories (one for async, one for basic), and the common infrastructure creation logic is delegated to another factory class. It moves a significant amount of the creation logic into the `impl` package, where it's easier to test. I think it's an improvement, but I'm very interested in your thoughts.
2. Pull Request #8 addresses the actual feature requirement in this issue, which is being able to easily get the same OpsLogger instance for multiple enums. My colleague @tarttelin had a great idea for that — simply store the most recently created instance and reuse it as long as no setter methods are called on the factory.

This was quite easy to implement once the factory logic had been refactored, and I am comfortable with making this a documented and supported part of the api. This fix has one significant implication, which is that `OpsLoggerFactory` is not thread-safe. However, it turns out that on closer inspection, OpsLoggerFactory was already not thread-safe, so I don't think this will have much impact.

What do you think? If you are happy with how this will work for your use case, then I'm ready to close this issue and create another release.

**Comment by ravn** [comment]
Hi @seanjreilly 

After working on Java 7 projects for the last couple of months I now have time to look at this again.  For us, this is an important feature, as we simply cannot consider our systems monolithic which is required for a global logging enum.  I think that pull request #8 is pragmatic enough for our usage, and I'll have a look at pull request #7.  Do you know if it is possible always to merge in pull requests with an actual merge commit so the pull request is visible in the commit tree as a separate branch?  It took me a while to identify that both were merged into master properly and not pending.  I'll have a closer look and report back.

I think a new release is appropriate.  Is this mature enough to warrant uploading to Maven Central?

**Comment by seanjreilly** [comment]
>Do you know if it is possible always to merge in pull requests with an actual merge commit so the pull request is visible in the commit tree as a separate branch?

I'm not sure, but I think that's what happened. https://github.com/EqualExperts/opslogger/commits/master shows two commits for merging the pull requests. The individual requests are included in the commit list as well...

>Is this mature enough to warrant uploading to Maven Central?

I know it's not MavenCentral, but I've been pushing releases to Jcenter for a while: https://bintray.com/equalexperts/open-source/opslogger/view

It's very easy to use jcenter dependencies from a maven project. If you click on "set me up!" on that link it has instructions for maven.

That being said, maybe maven central itself? To be honest, I've not looked into that process, but I've heard that it's a lot more work. If you've got any information on the process I'd love to hear it.

**Comment by ravn** [comment]
gitk did not show the pull request branches.  "git log --graph --oneline --all" did, though, so you were right.

I have nothing against JCentral, but if you need to specify yet another repository you are leaking the abstraction that maven "just knows" where to get your artifacts.  I went through the red tape with http://mvnrepository.com/artifact/dk.kewill.thirdpartymavencentral/jt400-full/7.10.  Perhaps with the source on github there is an easier approach - if the 0.3 release proves to be stable I'll have a look at it.

**Comment by seanjreilly** [comment]
Closing this in preparation for the 0.3.0 release.
